linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US

run:
  deadline: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
        - lll
  max-per-linter: 0
  max-same-issues: 0 